In [1]:
import numpy as np
print(np.__version__)

2.0.2

In [2]:
import pandas as pd

df = pd.DataFrame({
    "player": ["Kohli", "Rohit", "Dhoni", "Gill", "Pant"],
    "runs":   [73, 45, 28, 91, 34],
    "balls":  [49, 38, 17, 58, 22],
    "team":   ["RCB", "MI", "CSK", "GT", "DC"],
})

print(df)
print(df.shape)       # (rows, columns)
print(df.head(3))     # pehli 3 rows
print(df["runs"])     # ek column (Series)
print(df["runs"].mean())
print(df[df["runs"] > 40])   # filter, bilkul NumPy mask jaisa

  player  runs  balls team
0  Kohli    73     49  RCB
1  Rohit    45     38   MI
2  Dhoni    28     17  CSK
3   Gill    91     58   GT
4   Pant    34     22   DC
(5, 4)
  player  runs  balls team
0  Kohli    73     49  RCB
1  Rohit    45     38   MI
2  Dhoni    28     17  CSK
0    73
1    45
2    28
3    91
4    34
Name: runs, dtype: int64
54.2
  player  runs  balls team
0  Kohli    73     49  RCB
1  Rohit    45     38   MI
3   Gill    91     58   GT

In [7]:
df['strike_rate'] = (df['runs'] / df['balls'] * 100).round(2)

In [8]:
df

  player  runs  balls team  strike_rate
0  Kohli    73     49  RCB       148.98
1  Rohit    45     38   MI       118.42
2  Dhoni    28     17  CSK       164.71
3   Gill    91     58   GT       156.90
4   Pant    34     22   DC       154.55

In [10]:
print(df[df['strike_rate'] > 150])

  player  runs  balls team  strike_rate
2  Dhoni    28     17  CSK       164.71
3   Gill    91     58   GT       156.90
4   Pant    34     22   DC       154.55

In [11]:
print(df.groupby("team")["runs"].mean())

team
CSK    28.0
DC     34.0
GT     91.0
MI     45.0
RCB    73.0
Name: runs, dtype: float64

In [12]:
import pandas as pd
import numpy as np

df2 = pd.DataFrame({
    "player": ["A", "B", "C", "D", "E", "F"],
    "runs":   [73, 45, np.nan, 91, 34, 60],
    "balls":  [49, 38, 17, 58, 22, 40],
})

In [13]:
df2.isna().sum()

player    0
runs      1
balls     0
dtype: int64

In [16]:
df2.fillna(df2['runs'].mean())

  player  runs  balls
0      A  73.0     49
1      B  45.0     38
2      C  60.6     17
3      D  91.0     58
4      E  34.0     22
5      F  60.0     40